name: Build Workflow
 
run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'
 
on:
    push:
    pull_request:
    workflow_dispatch:
 
env:
  BRANCH_NAME: ${{github.ref_name}}
 
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Maven Build
        if: inputs.branch_name == 'main' || inputs.branch_name == 'master'
        shell: bash
        run: |
          ./mvn clean install -U \
            --batch-mode \
            -e \
            -Dmaven.build.cache.enabled=false \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -PcodeQuality

      - name: Maven Build -- Feature Branch
        if: inputs.branch_name != 'main' && inputs.branch_name != 'master'
        shell: bash
        run: |
          ./mvn clean install -U \
            --batch-mode \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Denforcer.skip=true \
            -PcodeQuality